/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/local-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local Session */
        post: operations["local_session_auth_local_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Enquiries
         * @description List enquiries with filters, full-text search, and cursor pagination (§4.2).
         */
        get: operations["list_enquiries_enquiries_get"];
        put?: never;
        /**
         * Ingest Enquiry
         * @description Ingest a new enquiry (A4). Computes code warnings on insert.
         */
        post: operations["ingest_enquiry_enquiries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enquiries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enquiry */
        get: operations["get_enquiry_enquiries__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enquiries/{enquiry_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Analysis
         * @description Start or reuse an analysis for an enquiry (single-flight, Fix 5).
         *
         *     Uses pg_advisory_xact_lock(enquiry_id) for the whole critical section:
         *     1. Check for an in-flight analysis (pending/in_progress) with same input_hash.
         *     2. If !force, check for a reusable completed analysis with same input_hash.
         *     3. Otherwise, allocate a new attempt number and create a new analysis + job.
         */
        post: operations["start_analysis_enquiries__enquiry_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Get analysis status, result, safety verdicts, and review prompt.
         */
        get: operations["get_analysis_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Analysis
         * @description Edit analysis result fields (§4.2, ADR-9).
         *
         *     Uses If-Match header for optimistic concurrency (version check).
         *     Only allowed when analysis.status == 'pending_review'.
         *     BLOCK verdict analyses are locked (no edits) unless admin override.
         */
        patch: operations["patch_analysis_analyses__analysis_id__patch"];
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Get job status (Fix 6).
         */
        get: operations["get_job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enquiries/{enquiry_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim Enquiry
         * @description Soft-claim an enquiry (ADR-9). Claims are not hard DB locks —
         *     they expire after CLAIM_TTL_MINUTES and can be overridden.
         */
        post: operations["claim_enquiry_enquiries__enquiry_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enquiries/{enquiry_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release Enquiry
         * @description Release a soft claim. Reviewers can only release their own claims;
         *     admins can release any claim.
         */
        post: operations["release_enquiry_enquiries__enquiry_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/resume-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Review
         * @description Resume a paused analysis review (§4.2, Fix 1, Fix 10).
         *
         *     Actions:
         *       - approve: approve the analysis as-is
         *       - edit_and_approve: apply edited_fields and approve
         *       - reject: reject the analysis
         *       - override_block: admin-only, override a BLOCK verdict
         *
         *     Validates:
         *       - expected_analysis_version matches current version
         *       - override_block requires admin role
         *       - typed_reason required for certain actions (reject, override_block, quarantine confirm)
         *       - edited_fields required for edit_and_approve and override_block
         */
        post: operations["resume_review_analyses__analysis_id__resume_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Review
         * @description POST /reviews — dismiss_false_positive (§4.2, Fix 1).
         *
         *     The only review action NOT tied to resuming the graph.
         *     Used to mark a safety verdict as a false positive without changing
         *     the analysis status.
         */
        post: operations["create_review_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Actions
         * @description GET /actions?enquiry_id= — list actions for an enquiry.
         */
        get: operations["list_actions_actions_get"];
        put?: never;
        /**
         * Create Actions
         * @description POST /actions — create action rows for outbound sends (Fix 2, Fix 3).
         *
         *     Precondition checks (independent of graph state):
         *       - analysis.status == 'approved'
         *       - verdict is not BLOCK
         *       - QUARANTINE must be confirmed (typed_reason provided)
         *       - destination must be enabled (tool_config)
         *       - breaker must not be open for the destination
         *       - expected_analysis_version must match
         *       - first send per (enquiry, destination) uses idempotency key enquiry_id:destination
         *       - resend requires resend=true and resend_reason
         */
        post: operations["create_actions_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Action
         * @description POST /actions/{id}/retry — retry a failed or unknown action (Fix 8).
         *
         *     For 'unknown' actions:
         *       - First attempts Tool.reconcile() automatically
         *       - If reconcile resolves, no confirm needed
         *       - If reconcile returns None, requires {confirm: true, typed_reason}
         *     For 'failed' actions: plain retry, no confirmation needed.
         */
        post: operations["retry_action_actions__action_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tools Metadata
         * @description GET /tools/metadata — tool UI metadata for destination chips.
         */
        get: operations["get_tools_metadata_tools_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sse Stream */
        get: operations["sse_stream_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Jobs
         * @description List jobs filtered by status (default: dead_letter).
         */
        get: operations["list_admin_jobs_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Job
         * @description Replay a dead_letter job: reset status='queued', attempts=0.
         */
        post: operations["replay_job_admin_jobs__id__replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tool Configs
         * @description GET /admin/tools — list all tool configs (secrets redacted).
         */
        get: operations["list_tool_configs_admin_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tools/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Tool Config
         * @description PUT /admin/tools/{key} — update a tool config.
         *
         *     Body: {enabled?: bool, config?: dict, credential?: str}
         */
        put: operations["update_tool_config_admin_tools__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisPatchRequest
         * @description Request body for PATCH /analyses/{id} — partial AnalysisOut edits.
         */
        AnalysisPatchRequest: {
            /** Summary */
            summary?: string | null;
            /** Category */
            category?: string | null;
            /** Priority */
            priority?: string | null;
            /** Reason */
            reason?: string | null;
            /** Suggested Action */
            suggested_action?: string | null;
            /** Missing Info */
            missing_info?: string[] | null;
            /** Risk Flags */
            risk_flags?: string[] | null;
            /** Needs Human Call */
            needs_human_call?: boolean | null;
        };
        /**
         * AnalysisRequest
         * @description Request body for POST /enquiries/{id}/analyses.
         */
        AnalysisRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * AnalysisResponse
         * @description Response for POST /enquiries/{id}/analyses (202).
         */
        AnalysisResponse: {
            /** Job Id */
            job_id: number | null;
            /** Analysis Id */
            analysis_id: string;
            /** Attached */
            attached: boolean;
            /** Reused */
            reused: boolean;
        };
        /**
         * AnalysisStatus
         * @description Response for GET /analyses/{id} — AnalysisStatus.
         */
        AnalysisStatus: {
            /** Id */
            id: string;
            /** Enquiry Id */
            enquiry_id: string;
            /** Analysis Attempt */
            analysis_attempt: number;
            /** Status */
            status: string;
            /** Result */
            result?: Record<string, never> | null;
            /** Llm Usage */
            llm_usage?: Record<string, never> | null;
            /** Model */
            model?: string | null;
            /** Version */
            version: number;
            /** Review Prompt */
            review_prompt?: Record<string, never> | null;
            /**
             * Safety Verdicts
             * @default []
             */
            safety_verdicts: Record<string, never>[];
            /** Job Id */
            job_id?: number | null;
            /**
             * Phase
             * @default queued
             */
            phase: string;
            /**
             * Node
             * @default queued
             */
            node: string;
        };
        /**
         * EnquiryIn
         * @description Ingest payload — matches the `enquiries` table's external fields.
         */
        EnquiryIn: {
            /**
             * Id
             * @description External id from ingest
             */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Email */
            email: string;
            /** Company */
            company: string;
            /**
             * Status
             * @description Source status
             */
            status: string;
            /** Message */
            message: string;
            /**
             * Received At
             * @description Defaults to now() if omitted
             */
            received_at?: string | null;
        };
        /**
         * EnquiryListOut
         * @description Response shape for GET /enquiries (§4.2: {items, next_cursor}).
         */
        EnquiryListOut: {
            /** Items */
            items: components["schemas"]["EnquiryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * EnquiryOut
         * @description Response shape for GET /enquiries, GET /enquiries/{id}.
         */
        EnquiryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Company */
            company: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Warning Missing Name */
            warning_missing_name: boolean;
            /** Warning Invalid Email */
            warning_invalid_email: boolean;
            /** Warning Domain Mismatch */
            warning_domain_mismatch: boolean;
            /** Warning Possible Duplicate */
            warning_possible_duplicate: boolean;
            /** Duplicate Of */
            duplicate_of: string | null;
            /** Claimed By */
            claimed_by: string | null;
            /** Claim Expires At */
            claim_expires_at: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Latest Analysis Id */
            latest_analysis_id?: string | null;
            /** Analysis Status */
            analysis_status?: string | null;
            /** Analysis Result */
            analysis_result?: Record<string, never> | null;
            /** Safety Decision */
            safety_decision?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatusResponse
         * @description Response for GET /jobs/{id} (Fix 6).
         */
        JobStatusResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Kind */
            kind: string;
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error?: string | null;
        };
        /**
         * ReviewDecisionRequest
         * @description Request body for POST /analyses/{id}/resume-review.
         */
        ReviewDecisionRequest: {
            /** Action */
            action: string;
            /** Reviewer Id */
            reviewer_id: string;
            /** Expected Analysis Version */
            expected_analysis_version: number;
            /** Edited Fields */
            edited_fields?: Record<string, never> | null;
            /** Typed Reason */
            typed_reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    local_session_auth_local_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_enquiries_enquiries_get: {
        parameters: {
            query?: {
                status?: string | null;
                company?: string | null;
                /** @description Filter by latest analysis priority */
                priority?: string | null;
                /** @description Filter by latest analysis category */
                category?: string | null;
                /** @description Filter by latest safety verdict */
                safety_verdict?: string | null;
                /** @description Full-text search */
                q?: string | null;
                /** @description received_at | company */
                sort?: string;
                /** @description Keyset cursor (received_at ISO of last item) */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnquiryListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_enquiry_enquiries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnquiryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enquiry_enquiries__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnquiryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_enquiries__enquiry_id__analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enquiry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_analysis_analyses__analysis_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "if-match"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_enquiry_enquiries__enquiry_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enquiry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_enquiry_enquiries__enquiry_id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enquiry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_review_analyses__analysis_id__resume_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_actions_actions_get: {
        parameters: {
            query: {
                /** @description Filter by enquiry_id */
                enquiry_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_actions_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_action_actions__action_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tools_metadata_tools_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    sse_stream_sse_get: {
        parameters: {
            query: {
                topics: string;
                last_event_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_jobs_admin_jobs_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_job_admin_jobs__id__replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tool_configs_admin_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    update_tool_config_admin_tools__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
